In [12]:
import numpy as np

In [5]:
np1 = np.array([])

In [6]:
np1

array([], dtype=float64)

In [10]:
type(np1)

numpy.ndarray

In [14]:
mat1 = np.array([[1,2],[3,4]])

In [15]:
mat1

array([[1, 2],
       [3, 4]])

In [17]:
np1.shape
mat1.shape

(2, 2)

In [18]:
mat1.dtype

dtype('int32')

In [19]:
mat1[0,0] = 5

In [20]:
mat1

array([[5, 2],
       [3, 4]])

In [22]:
mat2 = np.arange(0,10,1)

In [24]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
mat3 = np.linspace(0,10,20)

In [26]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
mat4 = np.random.rand(5,5)

In [28]:
mat4

array([[0.76704945, 0.66411698, 0.75427663, 0.28576905, 0.6787186 ],
       [0.27109767, 0.50580415, 0.86686381, 0.0585612 , 0.88363174],
       [0.29174875, 0.89061234, 0.11734369, 0.47612887, 0.42927262],
       [0.16985055, 0.24625475, 0.86281905, 0.24846434, 0.410289  ],
       [0.77581921, 0.54313077, 0.65300943, 0.5208327 , 0.05430693]])

In [29]:
mat5 = np.random.randn(5,5)
mat5

array([[ 1.19670121,  0.31445686, -1.42357207, -1.94788973, -0.2236178 ],
       [ 0.52934928, -0.4791397 , -2.10708645,  0.02661853, -0.33392245],
       [-0.27537321,  0.38873775, -0.13090498,  1.42253601, -0.37562737],
       [ 1.59900263,  0.14022245,  1.44889639,  0.56987396, -0.29862697],
       [ 0.12790059,  0.55795702, -0.35419103,  1.14488603, -0.65944468]])